webapp/haven/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),

    path('users/', include('identity.urls', namespace='identity')),

    path('projects/', include('projects.urls', namespace='projects')),

    path(
        'accounts/login/',
        auth_views.LoginView.as_view(template_name='identity/login.html'),
        name='login'
    ),

    path(
        'accounts/logout/',
        auth_views.LogoutView.as_view(),
        name='logout'
    ),


    path('', TemplateView.as_view(template_name='home.html'), name='home')
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

webapp/haven/projects/urls.py
from django.urls import path

from . import views


app_name = 'projects'

urlpatterns = [
    path('', views.ProjectList.as_view(), name='list'),
    path('new', views.ProjectCreate.as_view(), name='create'),

    path(
        '<int:pk>',
        views.ProjectDetail.as_view(),
        name='detail'
    ),

    path(
        '<int:pk>/participants/',
        views.ProjectListParticipants.as_view(),
        name='list_participants'
    ),

    path(
        '<int:pk>/participants/add',
        views.ProjectAddUser.as_view(),
        name='add_user'
    ),
]

webapp/haven/projects/models.py
from django.db import models, transaction

from data.models import Dataset
from identity.models import User

from .managers import ProjectQuerySet
from .roles import ProjectRole


class Project(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)

    datasets = models.ManyToManyField(Dataset, related_name='projects', blank=True)

    objects = ProjectQuerySet.as_manager()

    def __str__(self):
        return self.name

    @transaction.atomic
    def add_user(self, username, role, creator):
        """
        Add user to this project
        Creates user if they do not already exist

        :param username: username of user to add
        :param role: Role user will have on the project
        :param creator: `User` who is doing the adding
        """
        user, _ = User.objects.get_or_create(
            username=username,
            defaults={
                'created_by': creator,
            }
        )

        return Participant.objects.create(
            user=user,
            role=role,
            created_by=creator,
            project=self,
        )


class Participant(models.Model):
    """
    Represents a user's participation in a project
    """
    role = models.CharField(
        max_length=50,
        choices=ProjectRole.choices(),
        help_text="The participant's role on this project"
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey('projects.Project', on_delete=models.CASCADE)

    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text='Time the user was added to the project',
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='+',
        help_text='User who added this user to the project',
    )

    class Meta:
        unique_together = ('user', 'project')

    def __str__(self):
        return f'{self.user} ({self.get_role_display()} on {self.project})'

webapp/haven/projects/forms.py
from braces.forms import UserKwargModelFormMixin
from django import forms
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory

from identity.mixins import SaveCreatorMixin
from identity.models import User

from .models import Participant, Project
from .roles import ProjectRole


class ProjectForm(SaveCreatorMixin, forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description']


class ProjectAddUserForm(UserKwargModelFormMixin, forms.Form):
    username = forms.CharField(help_text='Username')
    role = forms.ChoiceField(
        choices=ProjectRole.choices(),
        help_text='Role on this project'
    )

    def clean_username(self):
        username = self.cleaned_data['username']

        if self.project.participant_set.filter(
            user__username=username
        ).exists():
            raise ValidationError("User is already on project")
        return username

    def save(self, **kwargs):
        role = self.cleaned_data['role']
        username = self.cleaned_data['username']
        return self.project.add_user(username, role, self.user)


class AddUserToProjectInlineForm(SaveCreatorMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['project'].queryset = Project.objects.get_editable_projects(self.user)

    class Meta:
        model = Participant
        fields = ('project', 'role')

    def clean(self):
        project = self.cleaned_data['project']
        role = ProjectRole(self.cleaned_data['role'])
        if not self.user.project_role(project).can_assign_role(role):
            raise ValidationError("You cannot assign the role on this project")


AddUsersToProjectInlineFormSet = inlineformset_factory(
    User,
    Participant,
    form=AddUserToProjectInlineForm,
    fk_name='user',
    extra=1
)

webapp/haven/projects/views.py
from braces.views import UserFormKwargsMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import OuterRef, Subquery
from django.urls import reverse
from django.views.generic import DetailView, ListView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import CreateView, FormMixin

from identity.mixins import UserRoleRequiredMixin
from identity.roles import UserRole

from .forms import ProjectAddUserForm, ProjectForm
from .models import Participant, Project
from .roles import ProjectRole


class SingleProjectMixin(SingleObjectMixin):
    model = Project

    def get_queryset(self):
        return super().get_queryset().get_visible_projects(self.request.user)

    def get_project_role(self):
        """Logged in user's role on the project"""
        return self.request.user.project_role(self.get_object())

    def get_context_data(self, **kwargs):
        kwargs['project_role'] = self.get_project_role()
        return super().get_context_data(**kwargs)


class ProjectCreate(
    LoginRequiredMixin, UserRoleRequiredMixin,
    UserFormKwargsMixin, CreateView
):
    model = Project
    form_class = ProjectForm

    user_roles = [UserRole.SYSTEM_CONTROLLER, UserRole.RESEARCH_COORDINATOR]

    def get_success_url(self):
        return reverse('projects:list')


class ProjectList(LoginRequiredMixin, ListView):
    context_object_name = 'projects'
    model = Project

    def get_queryset(self):
        # Store the user's project role on each participant
        participants = Participant.objects.filter(
            user=self.request.user, project=OuterRef('pk')
        )
        return super().get_queryset().\
            get_visible_projects(self.request.user).\
            annotate(your_role=Subquery(participants.values('role')[:1]))


class ProjectDetail(LoginRequiredMixin, SingleProjectMixin, DetailView):
    def get_context_data(self, **kwargs):
        kwargs['participant'] = self.request.user.get_participant(self.get_object())
        return super().get_context_data(**kwargs)


class ProjectAddUser(
    LoginRequiredMixin, UserPassesTestMixin,
    UserFormKwargsMixin, FormMixin, SingleProjectMixin, DetailView
):
    template_name = 'projects/project_add_user.html'
    form_class = ProjectAddUserForm

    def get_form(self):
        form = super().get_form()

        project_role = self.get_project_role()

        # Restrict form dropdown to roles this user is allowed to assign on the project
        form.project = self.get_object()
        form.fields['role'].choices = [
            (role, name)
            for (role, name) in form.fields['role'].choices
            if project_role.can_assign_role(ProjectRole(role))
        ]
        return form

    def get_success_url(self):
        obj = self.get_object()
        if self.get_project_role().can_list_participants:
            return reverse('projects:list_participants', args=[obj.id])
        else:
            return reverse('projects:detail', args=[obj.id])

    def test_func(self):
        return self.get_project_role().can_add_participants

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        self.object = self.get_object()
        if form.is_valid():
            form.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class ProjectListParticipants(
    LoginRequiredMixin, UserPassesTestMixin, SingleProjectMixin, DetailView
):
    template_name = 'projects/participant_list.html'

    def test_func(self):
        return self.get_project_role().can_list_participants

    def get_context_data(self, **kwargs):
        kwargs['participants'] = self.get_object().participant_set.all()
        return super().get_context_data(**kwargs)

webapp/haven/templates/projects/participant_list.html
{% extends "base.html" %}

{% block page_title %}{{ project.name }}: Participants{% endblock %}
{% block h1_title %}{{ project.name }}: Participants{% endblock %}

{% block content %}

<ul class="list-group">
  {% for participant in participants %}
  <li class="list-group-item">
    <div class="d-flex w-100 justify-content-between">
      <h4>{{ participant.get_role_display }}: {{ participant.user.username }}</a></h4>
      <small>added {{ participant.created_at }} by {{ participant.created_by }}</small>
    </div>
  </li>
  {% endfor %}
</ul>

<div class="my-3" role="group">
  {% if project_role.can_add_participants %}
    <a class="btn btn-primary btn-lg" href="{% url 'projects:add_user' project.id %}">Add User</a>
  {% endif %}
</div>

{% endblock %}


{% block crumbs %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url 'projects:list' %}">Projects</a></li>
  <li class="breadcrumb-item"><a href="{% url 'projects:detail' project.id %}">{{ project.name }}</a></li>
  <li class="breadcrumb-item active" aria-current="page">Participants</li>
{% endblock crumbs %}

webapp/haven/templates/projects/project_add_user.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block page_title %}{{ project.name }}: Add User{% endblock %}
{% block h1_title %}{{ project.name }}: Add User{% endblock %}

{% block content %}

<p>
{{ project.description }}
</p>

<div class="btn-group my-3" role="group">
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Add User</button>
  </form>
</div>

{% endblock content %}


{% block crumbs %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url 'projects:list' %}">Projects</a></li>
  <li class="breadcrumb-item"><a href="{% url 'projects:detail' project.id %}">{{ project.name }}</a></li>
  {% if project_role.can_list_participants %}
    <li class="breadcrumb-item"><a href="{% url 'projects:list_participants' project.id %}">Participants</a></li>
  {% else %}
    <li class="breadcrumb-item">Participants</li>
  {% endif %}
  <li class="breadcrumb-item active" aria-current="page">Add</li>
{% endblock crumbs %}

webapp/haven/templates/projects/project_detail.html
{% extends "base.html" %}

{% block page_title %}{{ project.name }}{% endblock %}
{% block h1_title %}{{ project.name }}{% endblock %}

{% block content %}

{% if participant %}
<p>
Role: {{ participant.get_role_display }}
</p>
{% endif %}

<p>
{{ project.description }}
</p>

<div class="my-3" role="group">
  {% if project_role.can_list_participants %}
    <a class="btn btn-primary btn-lg" href="{% url 'projects:list_participants' project.id %}">Participants</a>
  {% endif %}
</div>

<div class="my-3" role="group">
  {% if project_role.can_add_participants %}
    <a class="btn btn-primary btn-lg" href="{% url 'projects:add_user' project.id %}">Add User</a>
  {% endif %}
</div>

{% endblock content %}

{% block crumbs %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url 'projects:list' %}">Projects</a></li>
  <li class="breadcrumb-item active" aria-current="page">{{ project.name }}</li>
{% endblock crumbs %}

webapp/haven/templates/projects/project_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block h1_title %}Create Project{% endblock %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="btn btn-success">Save Project</button>
</form>

{% endblock content %}

{% block crumbs %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url 'projects:list' %}">Projects</a></li>
  <li class="breadcrumb-item active" aria-current="page">New</li>
{% endblock crumbs %}

webapp/haven/templates/projects/project_list.html
{% extends "base.html" %}
{% load project_tags %}

{% block page_title %}Projects{% endblock %}
{% block h1_title %}Projects{% endblock %}

{% block content %}
<ul class="list-group">
  {% for project in projects %}
  <li class="list-group-item">
    <div class="d-flex w-100 justify-content-between">
      <h4><a href="{% url "projects:detail" project.id %}">{{ project.name }}</a>
        {% if project.your_role %}
          ({{ project.your_role|project_role_display }})
        {% endif %}
      </h4>
      <small>{{ project.created_at }}</small>
    </div>
    <p>
    {{ project.description }}
    </p>
  </li>
  {% endfor %}
</ul>

<div class="btn-group my-3" role="group">
  {% if user.user_role.can_create_projects %}
    <a class="btn btn-primary btn-lg" href="{% url 'projects:create' %}">Create Project</a>
  {% endif %}
</div>

{% endblock content %}

{% block crumbs %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
  <li class="breadcrumb-item active" aria-current="page">Projects</li>
{% endblock crumbs %}