webapp/haven/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),

    path('users/', include('identity.urls', namespace='identity')),

    path('projects/', include('projects.urls', namespace='projects')),

    path(
        'accounts/login/',
        auth_views.LoginView.as_view(template_name='identity/login.html'),
        name='login'
    ),

    path(
        'accounts/logout/',
        auth_views.LogoutView.as_view(),
        name='logout'
    ),


    path('', TemplateView.as_view(template_name='home.html'), name='home')
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

webapp/haven/identity/urls.py
from django.urls import path

from . import views


app_name = 'identity'

urlpatterns = [
    path('new', views.UserCreate.as_view(), name='add_user'),
]

webapp/haven/projects/urls.py
from django.urls import path

from . import views


app_name = 'projects'

urlpatterns = [
    path('', views.ProjectList.as_view(), name='list'),
    path('new', views.ProjectCreate.as_view(), name='create'),

    path(
        '<int:pk>',
        views.ProjectDetail.as_view(),
        name='detail'
    ),

    path(
        '<int:pk>/participants/',
        views.ProjectListParticipants.as_view(),
        name='list_participants'
    ),

    path(
        '<int:pk>/participants/add',
        views.ProjectAddUser.as_view(),
        name='add_user'
    ),
]

webapp/haven/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title>{% block page_title %}Home{% endblock %} | Data Safe Haven</title>
  </head>
  <body>

     <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
       <a class="navbar-brand" href="{% url 'home' %}">Data Safe Haven</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          {% if request.user.is_authenticated %}
            {% if request.user.user_role.can_create_users %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'identity:add_user' %}">Create User</a>
            </li>
            {% endif %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'projects:list' %}">Projects</a>
            </li>
            {% endif %}
        </ul>

        <span class="navbar-text">
          {% if request.user.is_authenticated %}
            Logged in as {{ request.user.username }}
          {% else %}
          <a class="nav-link" href="{% url 'login' %}">Log In</a>
          {% endif %}
        </span>

        {% if request.user.is_authenticated %}
          <span class="navbar-text">
            <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
          </span>
        {% endif %}
      </div>
    </nav>

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        {% block crumbs %}
        {% endblock %}
      </ol>
    </nav>

    <main role="main" class="container">
      <div class="row">
        <div class="col-lg mt-4">
          <h1>{% block h1_title %}Data Safe Haven{% endblock %}</h1>
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

webapp/haven/templates/home.html
{% extends "base.html" %}

{% block content %}
  <p class="lead">
    Welcome to the data safe haven
  </p>
{% endblock content %}